app:
    resource: "@AppBundle/Controller/"
    type: annotation

internal_api_snapshots:
    #removing the .php creates errors, seems a little strange but it does work
    resource: "@AppBundle/Controller/InternalAPI/SnapshotController.php"
    type: rest
    prefix: /internal-api

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register-user

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
