services:
    property_manager:
        class:  AppBundle\Manager\PropertyManager
        arguments: 
            entityManager: "@doctrine.orm.entity_manager"

    customer_manager:
        class:  AppBundle\Manager\CustomerManager
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    user_manager:
        class:  AppBundle\Manager\UserManager
        arguments:
            propertyManager: "@property_manager"

    snapshot_manager:
        class:  AppBundle\Manager\SnapshotManager
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    queue_manager:
        class: AppBundle\Manager\QueueManager
        arguments:
          host: "%queue_host%"
          post: "%queue_port%"
          mirror_directory: "%kernel.root_dir%/../web/mirror"

    registration_form_handler:
        class: AppBundle\Form\Handler\RegistrationFormHandler
        scope: request
        public: false
        arguments:
          - "@fos_user.registration.form"
          - "@request"
          - "@fos_user.user_manager"
          - "@fos_user.mailer"
          - "@fos_user.util.token_generator"
          - "@customer_manager"

    snapshot_subscriber:
        class: AppBundle\EventListener\SnapshotSubscriber
        arguments:
          queueManager: "@queue_manager"
        tags:
          - { name: doctrine.event_subscriber }

    resource_subscriber:
        class: AppBundle\EventListener\ResourceSubscriber
        arguments:
          queueManager: "@queue_manager"
        tags:
          - { name: doctrine.event_subscriber }
