<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Customer;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyRepository extends EntityRepository
{
    public function getPropertiesForCustomer(Customer $customer)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:Property p WHERE p.customerId = :customer_id')
            ->setParameter('customer_id', $customer->getId());

        return $query->getResult();
    }

    public function getPropertiesWithPathsForCustomer(Customer $customer)
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT p, pa FROM AppBundle:Property p
                LEFT JOIN p.paths pa WHERE p.customerId = :customer_id'
            )->setParameter('customer_id', $customer->getId());

        return $query->getResult();
    }
}
