<?php

namespace Heron\MonitorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JavascriptFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JavascriptFileRepository extends EntityRepository
{
}
