<?php

namespace Heron\MonitorBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Heron\MonitorBundle\Entity\Customer;

/**
 * PropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyRepository extends EntityRepository
{
    public function getPropertiesForCustomer(Customer $customer)
    {
        $query = $this->getEntityManager()
        ->createQuery(
            'SELECT p FROM HeronMonitorBundle:Property p
            JOIN p.customer c WHERE c.id = :customer_id'
        )->setParameter('customer_id', $customer->getId()); 

        return $query->getResult();
    }
}
