parameters:
#    heron_monitor.example.class: Heron\MonitorBundle\Example

services:
#    heron_monitor.example:
#        class: %heron_monitor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
